version: "3.9"

services:
  ansible_host:
    build:
      context: .
      dockerfile: containers/build/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./ansible:/ansible
    ports:
      - "8000:8000"
      - "22:22"